"""rename strength to strengths in CVExtraction

Revision ID: 93663cf224f6
Revises: 2cfcf02c0c17
Create Date: 2025-09-26 09:54:32.499852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93663cf224f6'
down_revision: Union[str, Sequence[str], None] = '2cfcf02c0c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
